// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.2
// source: calcpb/chat.proto

package calcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdditionRequestFromUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstNumber  int32 `protobuf:"varint,1,opt,name=FirstNumber,proto3" json:"FirstNumber,omitempty"`
	SecondNumber int32 `protobuf:"varint,2,opt,name=SecondNumber,proto3" json:"SecondNumber,omitempty"`
	Operation    int32 `protobuf:"varint,3,opt,name=Operation,proto3" json:"Operation,omitempty"`
}

func (x *AdditionRequestFromUser) Reset() {
	*x = AdditionRequestFromUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calcpb_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdditionRequestFromUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdditionRequestFromUser) ProtoMessage() {}

func (x *AdditionRequestFromUser) ProtoReflect() protoreflect.Message {
	mi := &file_calcpb_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdditionRequestFromUser.ProtoReflect.Descriptor instead.
func (*AdditionRequestFromUser) Descriptor() ([]byte, []int) {
	return file_calcpb_chat_proto_rawDescGZIP(), []int{0}
}

func (x *AdditionRequestFromUser) GetFirstNumber() int32 {
	if x != nil {
		return x.FirstNumber
	}
	return 0
}

func (x *AdditionRequestFromUser) GetSecondNumber() int32 {
	if x != nil {
		return x.SecondNumber
	}
	return 0
}

func (x *AdditionRequestFromUser) GetOperation() int32 {
	if x != nil {
		return x.Operation
	}
	return 0
}

type AdditionResponseFromServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstNum  int32 `protobuf:"varint,1,opt,name=FirstNum,proto3" json:"FirstNum,omitempty"`
	SecondNum int32 `protobuf:"varint,2,opt,name=SecondNum,proto3" json:"SecondNum,omitempty"`
	Sum       int32 `protobuf:"varint,3,opt,name=Sum,proto3" json:"Sum,omitempty"`
}

func (x *AdditionResponseFromServer) Reset() {
	*x = AdditionResponseFromServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calcpb_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdditionResponseFromServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdditionResponseFromServer) ProtoMessage() {}

func (x *AdditionResponseFromServer) ProtoReflect() protoreflect.Message {
	mi := &file_calcpb_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdditionResponseFromServer.ProtoReflect.Descriptor instead.
func (*AdditionResponseFromServer) Descriptor() ([]byte, []int) {
	return file_calcpb_chat_proto_rawDescGZIP(), []int{1}
}

func (x *AdditionResponseFromServer) GetFirstNum() int32 {
	if x != nil {
		return x.FirstNum
	}
	return 0
}

func (x *AdditionResponseFromServer) GetSecondNum() int32 {
	if x != nil {
		return x.SecondNum
	}
	return 0
}

func (x *AdditionResponseFromServer) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

var File_calcpb_chat_proto protoreflect.FileDescriptor

var file_calcpb_chat_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x61, 0x6c, 0x63, 0x70, 0x62, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x61, 0x6c, 0x63, 0x70, 0x62, 0x22, 0x7d, 0x0a, 0x17, 0x41,
	0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x72,
	0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x46, 0x69, 0x72,
	0x73, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x68, 0x0a, 0x1a, 0x41, 0x64,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46, 0x72,
	0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x72, 0x73,
	0x74, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x46, 0x69, 0x72, 0x73,
	0x74, 0x4e, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x4e, 0x75,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x4e,
	0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x53, 0x75, 0x6d, 0x32, 0x62, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x12, 0x56, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x1f, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72,
	0x1a, 0x22, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x63, 0x61,
	0x6c, 0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calcpb_chat_proto_rawDescOnce sync.Once
	file_calcpb_chat_proto_rawDescData = file_calcpb_chat_proto_rawDesc
)

func file_calcpb_chat_proto_rawDescGZIP() []byte {
	file_calcpb_chat_proto_rawDescOnce.Do(func() {
		file_calcpb_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_calcpb_chat_proto_rawDescData)
	})
	return file_calcpb_chat_proto_rawDescData
}

var file_calcpb_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_calcpb_chat_proto_goTypes = []interface{}{
	(*AdditionRequestFromUser)(nil),    // 0: calcpb.AdditionRequestFromUser
	(*AdditionResponseFromServer)(nil), // 1: calcpb.AdditionResponseFromServer
}
var file_calcpb_chat_proto_depIdxs = []int32{
	0, // 0: calcpb.Services.ChatService:input_type -> calcpb.AdditionRequestFromUser
	1, // 1: calcpb.Services.ChatService:output_type -> calcpb.AdditionResponseFromServer
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calcpb_chat_proto_init() }
func file_calcpb_chat_proto_init() {
	if File_calcpb_chat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calcpb_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdditionRequestFromUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calcpb_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdditionResponseFromServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calcpb_chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calcpb_chat_proto_goTypes,
		DependencyIndexes: file_calcpb_chat_proto_depIdxs,
		MessageInfos:      file_calcpb_chat_proto_msgTypes,
	}.Build()
	File_calcpb_chat_proto = out.File
	file_calcpb_chat_proto_rawDesc = nil
	file_calcpb_chat_proto_goTypes = nil
	file_calcpb_chat_proto_depIdxs = nil
}
